### ISSUE TITLE
Rebuilding ic-repl results in reqwest error

### ISSUE THREAD

**Issue by jzxchiang1** [chenyan2002/ic-repl#18]
I recently rebuilt ic-repl locally from the latest master, but when I ran it I got this error:

```
thread 'main' panicked at 'Could not create HTTP client.: reqwest::Error { kind: Builder, source: "Unknown TLS backend passed to `use_preconfigured_tls`" }', /Users/justinchiang/.cargo/registry/src/github.com-1ecc6299db9ec823/ic-agent-0.9.0/src/agent/http_transport.rs:93:18
```

This is due to some dependency issues with ic-agent, which is itself a dependency of ic-repl. To fix locally, you should do this in Cargo.toml in your local ic-repl repro and rebuild:

```
-ic-agent = "0.9.0"
+ic-agent = { git = "https://github.com/dfinity/agent-rs" }
```

Temporary fix until they publish a new version. Then ic-repl should update the ic-agent version.

**Comment by chenyan2002** [comment]
I think this is resolved
