### ISSUE TITLE
Feature request: Switching to anonymous identity

### ISSUE THREAD

**Issue by bioerrorlog** [chenyan2002/ic-repl#21]
There is no way to switch back to an anonymous identity after using an identity command.

If it becomes possible, ic-repl would be more useful for writing anonymous testing scenarios.

Related forum post:
[Canister test by ic-repl: how to set anonymous identity?](https://forum.dfinity.org/t/canister-test-by-ic-repl-how-to-set-anonymous-identity/10957)

**Comment by chenyan2002** [comment]
Add `identity anonymous`
