### ISSUE TITLE
m1 mac installation

### ISSUE THREAD

**Issue by letmejustputthishere** [chenyan2002/ic-repl#22]
seems like i can't use the binary from the lates release out of the box. 
i get the following error when running `ic-repl`:
```
❯ ic-repl
dyld[56920]: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /usr/local/bin/ic-repl
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file)
[1]    56920 abort      ic-repl
```

i tried solving it by running 
```
❯ sudo ln -sfn /opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib /usr/local/lib/libssl.1.1.dylib
```

but this lead to this new error:
```
❯ ic-repl
dyld[57026]: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /usr/local/bin/ic-repl
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libssl.1.1.dylib' (no such file)
[1]    57026 abort      ic-repl
```

then i installed an `x86_64` version of `homebrew` following the instructions [here](https://noahpeeters.de/posts/apple-silicon/homebrew-setup/) and installed `openssl@1.1` again using it, which finally worked.

maybe the process can be simplified?

**Comment by chenyan2002** [comment]
I don't have M1, so I cannot test it. Does `cargo build` from master work? You can also try build with feature `static-ssl` enabled.

**Comment by letmejustputthishere** [comment]
`cargo build` worked, although i don't know if this is due to the above step of using the `x86_64` version of `homebrew`. Will close this issue anyways, thanks for the quick response!ls
