### ISSUE TITLE
add loops

### ISSUE THREAD

**Issue by letmejustputthishere** [chenyan2002/ic-repl#23]
is it possible to use loops in ic-repl and if not, can this feature be added?

**Comment by chenyan2002** [comment]
No plan to support it in the short term. The script has no control flow at the moment.

One hacky workaround is to use environment variable and external program to drive the control flow. For example,

a.ic-repl.sh
```
call ${CANISTER_ID}.greet("${MSG}")
```

Then you can use `bash` or other binary to set the environment variable and call `ic-repl a.ic-repl.sh`.

**Comment by letmejustputthishere** [comment]
ahh that's smart, thank you!
