### ISSUE TITLE
Update to 0.12 

### ISSUE THREAD

**Issue by gabrielnic** [chenyan2002/ic-repl#44]
The update the dfx 0.12 based on this  https://github.com/dfinity/sdk/blob/master/docs/migration/dfx-0.12.0-migration-guide.md
Implies the dfx port is now by default on port 4943 but I can't find a way to set the port. 

Ping http://localhost:8000/. should go to 4943 now.

**Comment by chenyan-dfinity** [comment]
If you use the latest `ic-repl`, the default port is already 4943. If you want to specify other replica URL, you can use `ic-repl -r http://localhost:8080` or `ic-repl -r ic` to point to the main net.

**Comment by gabrielnic** [comment]
my god, I feel stupid, I looked for this change a lot but didn't see it, thank you very much
